# Generated by Django 3.2.6 on 2021-10-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_langs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo_100',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
