# Generated by Django 3.2.6 on 2021-10-01 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_photo_100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='photo_100',
            new_name='photo_max',
        ),
    ]
