# Generated by Django 3.2.6 on 2021-10-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_photo_100_userprofile_photo_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo_max',
            field=models.TextField(blank=True, verbose_name='Фото'),
        ),
    ]
