# Generated by Django 3.2.6 on 2021-10-01 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userprofile_photo_max'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='photo_max',
        ),
    ]
