# Generated by Django 3.2.6 on 2021-09-23 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductsCategory',
        ),
    ]
